project_id = "obiiwmdcykfredsbhmoc"

[functions.analyze-text]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.content-chat]
verify_jwt = false

[functions.gumroad-webhook]
verify_jwt = false

[functions.generate-podcast]
verify_jwt = false
